/*
 * SmartCard — Business Card Scanner Application
 * Copyright (c) 2026 Arnon Arpaket. All rights reserved.
 *
 * This file is part of SmartCard, a proprietary software product.
 * Unauthorized copying, modification, distribution, or use is prohibited.
 */

import type { EventField } from "./supabase/types";

export type EventTemplate = {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  fields: EventField[];
};

export const EVENT_TEMPLATES: EventTemplate[] = [
  {
    id: "blank",
    name: "เริ่มจากศูนย์",
    description: "สร้าง field เองทั้งหมด เหมาะสำหรับ event แบบเฉพาะตัว",
    icon: "✏️",
    color: "bg-slate-100 text-slate-700",
    fields: [],
  },
  {
    id: "trade-show",
    name: "งานแสดงสินค้า",
    description: "Thaifex, Anuga, Food Expo — เก็บประเภทธุรกิจ + สินค้าที่สนใจ + follow-up",
    icon: "🎪",
    color: "bg-blue-100 text-blue-700",
    fields: [
      {
        type: "multiselect",
        key: "businessType",
        labelTh: "ประเภทธุรกิจ",
        labelEn: "Type of Business",
        options: [
          "Manufacturer",
          "Wholesaler",
          "Restaurant/Café",
          "Hotel",
          "Supermarket",
          "Convenience Store",
          "Importer",
          "Distributor",
          "Online",
        ],
        allowOther: true,
      },
      {
        type: "multiselect",
        key: "interestedProducts",
        labelTh: "กลุ่มสินค้าที่สนใจ",
        labelEn: "Interested Products",
        options: [
          "Beef",
          "Pork",
          "Chicken",
          "Lamb",
          "Seafood",
          "Vegetables",
          "Fruits",
          "Bakery",
          "Dairy",
          "Frozen Food",
          "Ready-to-eat",
        ],
        allowOther: true,
      },
      {
        type: "multiselect",
        key: "interestLevel",
        labelTh: "ระดับความสนใจ",
        labelEn: "Interest Level",
        options: ["สูง / High", "ปานกลาง / Medium", "ต่ำ / Low"],
      },
      {
        type: "multiselect",
        key: "followUp",
        labelTh: "Follow Up",
        labelEn: "Follow Up",
        options: [
          "ส่งใบเสนอราคา / Quotation",
          "ส่งตัวอย่าง / Sample",
          "ส่งข้อมูลสินค้า / Product Info",
          "นัดเยี่ยม / Schedule Visit",
        ],
        allowOther: true,
      },
      {
        type: "textarea",
        key: "notes",
        labelTh: "หมายเหตุ",
        labelEn: "Notes",
        rows: 3,
      },
    ],
  },
  {
    id: "customer-visit",
    name: "ลูกค้าเข้าเยี่ยม",
    description: "เก็บจุดประสงค์การเยี่ยม สินค้าที่นำเสนอ และ action items",
    icon: "🤝",
    color: "bg-emerald-100 text-emerald-700",
    fields: [
      {
        type: "multiselect",
        key: "purpose",
        labelTh: "จุดประสงค์การเยี่ยม",
        labelEn: "Purpose of Visit",
        options: [
          "ดูสินค้า / Product Demo",
          "เจรจาธุรกิจ / Business Discussion",
          "ทำสัญญา / Contract",
          "ขอข้อมูล / Information",
          "จับคู่ทางธุรกิจ / Business Matching",
          "เยี่ยมเยือน / Courtesy Visit",
        ],
        allowOther: true,
      },
      {
        type: "textarea",
        key: "productsDiscussed",
        labelTh: "สินค้าที่นำเสนอ/พูดคุย",
        labelEn: "Products Discussed",
        rows: 3,
      },
      {
        type: "multiselect",
        key: "interestLevel",
        labelTh: "ความสนใจ",
        labelEn: "Interest Level",
        options: ["สูงมาก", "สูง", "ปานกลาง", "ต่ำ", "ยังไม่แน่ใจ"],
      },
      {
        type: "textarea",
        key: "nextSteps",
        labelTh: "ขั้นตอนถัดไป",
        labelEn: "Next Steps",
        rows: 3,
      },
      {
        type: "textarea",
        key: "notes",
        labelTh: "หมายเหตุ",
        labelEn: "Notes",
        rows: 2,
      },
    ],
  },
  {
    id: "sales-lead",
    name: "ลีดขาย / Sales Lead",
    description: "เก็บข้อมูลสำหรับ pipeline การขาย — source, stage, budget, timeline",
    icon: "💰",
    color: "bg-amber-100 text-amber-700",
    fields: [
      {
        type: "multiselect",
        key: "leadSource",
        labelTh: "แหล่งที่มา",
        labelEn: "Lead Source",
        options: [
          "Cold Call",
          "Referral",
          "Website",
          "Trade Show",
          "Email Campaign",
          "Social Media",
          "Walk-in",
          "Existing Customer",
        ],
        allowOther: true,
      },
      {
        type: "multiselect",
        key: "leadStage",
        labelTh: "Lead Stage",
        labelEn: "Lead Stage",
        options: [
          "New",
          "Qualified",
          "Proposal Sent",
          "Negotiation",
          "Closed Won",
          "Closed Lost",
        ],
      },
      {
        type: "text",
        key: "budgetRange",
        labelTh: "งบประมาณโดยประมาณ",
        labelEn: "Estimated Budget",
        placeholder: "เช่น 100K-500K THB",
      },
      {
        type: "multiselect",
        key: "decisionTimeline",
        labelTh: "ระยะเวลาตัดสินใจ",
        labelEn: "Decision Timeline",
        options: [
          "ภายใน 1 เดือน",
          "1-3 เดือน",
          "3-6 เดือน",
          "6-12 เดือน",
          "มากกว่า 12 เดือน",
        ],
      },
      {
        type: "text",
        key: "decisionMaker",
        labelTh: "ผู้ตัดสินใจ",
        labelEn: "Decision Maker",
        placeholder: "ชื่อ/ตำแหน่ง",
      },
      {
        type: "textarea",
        key: "painPoints",
        labelTh: "ปัญหาที่ลูกค้ามี",
        labelEn: "Pain Points",
        rows: 3,
      },
      {
        type: "textarea",
        key: "notes",
        labelTh: "หมายเหตุ",
        labelEn: "Notes",
        rows: 2,
      },
    ],
  },
  {
    id: "networking",
    name: "งาน Networking",
    description: "งานสังสรรค์ — แนะนำโดยใคร, หัวข้อที่คุย, ความเชื่อมโยง",
    icon: "🌐",
    color: "bg-violet-100 text-violet-700",
    fields: [
      {
        type: "text",
        key: "introducedBy",
        labelTh: "แนะนำโดย",
        labelEn: "Introduced By",
        placeholder: "ชื่อคนที่แนะนำ (ถ้ามี)",
      },
      {
        type: "multiselect",
        key: "topics",
        labelTh: "หัวข้อที่คุยกัน",
        labelEn: "Topics Discussed",
        options: [
          "Business",
          "Technology",
          "Marketing",
          "Sales",
          "Operations",
          "HR",
          "Finance",
          "Industry Trends",
        ],
        allowOther: true,
      },
      {
        type: "multiselect",
        key: "potentialCollab",
        labelTh: "โอกาสร่วมงาน",
        labelEn: "Collaboration Potential",
        options: [
          "ลูกค้า / Customer",
          "ผู้ขาย / Vendor",
          "พาร์ทเนอร์ / Partner",
          "ที่ปรึกษา / Advisor",
          "นักลงทุน / Investor",
          "เพื่อน / Friend",
        ],
        allowOther: true,
      },
      {
        type: "multiselect",
        key: "followUp",
        labelTh: "Follow Up",
        labelEn: "Follow Up",
        options: [
          "ส่งข้อมูล / Send Info",
          "นัดทานข้าว / Lunch/Dinner",
          "นัดประชุม / Schedule Meeting",
          "แนะนำคนอื่น / Connect Others",
          "เก็บไว้เป็น contact",
        ],
        allowOther: true,
      },
      {
        type: "textarea",
        key: "notes",
        labelTh: "หมายเหตุ",
        labelEn: "Notes",
        rows: 3,
      },
    ],
  },
  {
    id: "conference",
    name: "ประชุม / Conference",
    description: "เข้าร่วม session — เก็บความสนใจของผู้ฟัง",
    icon: "🎤",
    color: "bg-rose-100 text-rose-700",
    fields: [
      {
        type: "text",
        key: "session",
        labelTh: "ห้อง/Session ที่เข้า",
        labelEn: "Session Attended",
      },
      {
        type: "multiselect",
        key: "topicsInterested",
        labelTh: "หัวข้อที่สนใจ",
        labelEn: "Topics of Interest",
        options: [
          "Innovation",
          "Sustainability",
          "Technology",
          "Marketing",
          "Operations",
          "Leadership",
          "Industry Trends",
          "Case Studies",
        ],
        allowOther: true,
      },
      {
        type: "multiselect",
        key: "interestLevel",
        labelTh: "ระดับความสนใจ",
        labelEn: "Interest Level",
        options: ["สูงมาก", "สูง", "ปานกลาง", "ต่ำ"],
      },
      {
        type: "textarea",
        key: "keyTakeaways",
        labelTh: "ประเด็นสำคัญที่คุย",
        labelEn: "Key Takeaways",
        rows: 3,
      },
      {
        type: "textarea",
        key: "notes",
        labelTh: "หมายเหตุ",
        labelEn: "Notes",
        rows: 2,
      },
    ],
  },
  {
    id: "simple-note",
    name: "หมายเหตุย่อๆ",
    description: "แค่ tag ประเภทกับ note สั้นๆ — เหมาะสำหรับงานแบบ casual",
    icon: "📝",
    color: "bg-cyan-100 text-cyan-700",
    fields: [
      {
        type: "multiselect",
        key: "tag",
        labelTh: "ประเภท",
        labelEn: "Tag",
        options: [
          "ลูกค้า / Customer",
          "ผู้สนใจ / Prospect",
          "คู่ค้า / Partner",
          "Vendor",
          "VIP",
        ],
        allowOther: true,
      },
      {
        type: "textarea",
        key: "notes",
        labelTh: "หมายเหตุ",
        labelEn: "Notes",
        rows: 5,
      },
    ],
  },
  {
    id: "recruitment",
    name: "Recruitment Fair",
    description: "งานสมัครงาน — เก็บตำแหน่งสนใจ + experience",
    icon: "👔",
    color: "bg-indigo-100 text-indigo-700",
    fields: [
      {
        type: "multiselect",
        key: "interestedPosition",
        labelTh: "ตำแหน่งที่สนใจ",
        labelEn: "Interested Position",
        options: [
          "Sales",
          "Marketing",
          "Operations",
          "HR",
          "Finance",
          "IT",
          "R&D",
          "Production",
          "Logistics",
        ],
        allowOther: true,
      },
      {
        type: "multiselect",
        key: "experienceLevel",
        labelTh: "ระดับประสบการณ์",
        labelEn: "Experience Level",
        options: [
          "Fresh Graduate",
          "1-3 ปี",
          "3-5 ปี",
          "5-10 ปี",
          "มากกว่า 10 ปี",
        ],
      },
      {
        type: "text",
        key: "expectedSalary",
        labelTh: "เงินเดือนคาดหวัง",
        labelEn: "Expected Salary",
      },
      {
        type: "multiselect",
        key: "availability",
        labelTh: "พร้อมเริ่มงาน",
        labelEn: "Availability",
        options: ["ทันที", "1 เดือน", "2-3 เดือน", "ระยะยาว"],
      },
      {
        type: "textarea",
        key: "notes",
        labelTh: "หมายเหตุ/ความประทับใจ",
        labelEn: "Notes",
        rows: 3,
      },
    ],
  },
];

export function getTemplate(id: string): EventTemplate | undefined {
  return EVENT_TEMPLATES.find((t) => t.id === id);
}
